# Generated by Django 4.2.1 on 2023-05-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_enrollment_duedate_enrollment_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='date_of_birth',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='duedate',
            new_name='DueDate',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='fullname',
            new_name='FullName',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='phonenumber',
            new_name='PhoneNumber',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='pymentstatus',
            new_name='PymentStatus',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='reference',
            new_name='Reference',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='selectmembershipplan',
            new_name='SelectMembershipplan',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='selecttrainer',
            new_name='SelectTrainer',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='timestamp',
            new_name='TimeStamp',
        ),
    ]
