# Generated by Django 4.2.1 on 2023-05-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_rename_address_enrollment_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
    ]
