# Generated by Django 4.2.1 on 2023-05-16 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_timestamp_enrollment_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='timeStamp',
            new_name='timestamp',
        ),
    ]
